
package org.russianpost.fclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ItemDataService", targetNamespace = "http://fclient.russianpost.org", wsdlLocation = "https://tracking.russianpost.ru/tracking-web-static/fc_wsdl.xml")
public class ItemDataService
    extends Service
{

    private final static URL ITEMDATASERVICE_WSDL_LOCATION;
    private final static WebServiceException ITEMDATASERVICE_EXCEPTION;
    private final static QName ITEMDATASERVICE_QNAME = new QName("http://fclient.russianpost.org", "ItemDataService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://tracking.russianpost.ru/tracking-web-static/fc_wsdl.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITEMDATASERVICE_WSDL_LOCATION = url;
        ITEMDATASERVICE_EXCEPTION = e;
    }

    public ItemDataService() {
        super(__getWsdlLocation(), ITEMDATASERVICE_QNAME);
    }

    public ItemDataService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITEMDATASERVICE_QNAME, features);
    }

    public ItemDataService(URL wsdlLocation) {
        super(wsdlLocation, ITEMDATASERVICE_QNAME);
    }

    public ItemDataService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITEMDATASERVICE_QNAME, features);
    }

    public ItemDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItemDataService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FederalClient
     */
    @WebEndpoint(name = "ItemDataServicePort")
    public FederalClient getItemDataServicePort() {
        return super.getPort(new QName("http://fclient.russianpost.org", "ItemDataServicePort"), FederalClient.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FederalClient
     */
    @WebEndpoint(name = "ItemDataServicePort")
    public FederalClient getItemDataServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fclient.russianpost.org", "ItemDataServicePort"), FederalClient.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITEMDATASERVICE_EXCEPTION!= null) {
            throw ITEMDATASERVICE_EXCEPTION;
        }
        return ITEMDATASERVICE_WSDL_LOCATION;
    }

}
